module LocationTracker exposing (..)

import ItemTracker exposing (ItemTracker)
import Logic exposing (..)



-- Name of Location
-- Check Function (ItemTracker -> Bool)
-- Plaintext list of requirements


type alias Location =
    { name : String
    , label : String
    , tags : List String
    , region : String
    , canGet : ItemTracker -> Bool
    }


initLocations : List Location
initLocations =
    -- Bottom of the Well
    [ Location "Bottom of the Well Front Left Fake Wall Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" canUseLensOfTruth
    , Location "Bottom of the Well Front Center Bombable Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" hasExplosives
    , Location "Bottom of the Well Back Left Bombable Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" (\tracker -> (tracker |> hasExplosives) && (tracker |> canUseLensOfTruth))
    , Location "Bottom of the Well Underwater Left Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" canPlayZelda
    , Location "Bottom of the Well Freestanding Key" "Collectable" [ "Bottom of the Well" ] "Bottom of the Well" (\tracker -> (tracker |> hasDekuSticks) || (tracker |> canUseDinsFire))
    , Location "Bottom of the Well Compass Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" canUseLensOfTruth
    , Location "Bottom of the Well Center Skulltula Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" canUseLensOfTruth
    , Location "Bottom of the Well Right Bottom Fake Wall Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" canUseLensOfTruth
    , Location "Bottom of the Well Fire Keese Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" (\tracker -> (tracker.smallKeys.well >= 3) && (tracker |> canUseLensOfTruth))
    , Location "Bottom of the Well Like Like Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" (\tracker -> (tracker.smallKeys.well >= 3) && (tracker |> canUseLensOfTruth))
    , Location "Bottom of the Well Map Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" (\tracker -> (tracker |> hasExplosives) || ((((tracker.smallKeys.well >= 3) && (tracker |> canUseLensOfTruth)) || (tracker |> canUseDinsFire)) && (tracker |> hasGoronBracer)))
    , Location "Bottom of the Well Underwater Front Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" canPlayZelda
    , Location "Bottom of the Well Invisible Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" (\tracker -> (tracker |> canPlayZelda) && (tracker |> canUseLensOfTruth))
    , Location "Bottom of the Well Lens of Truth Chest" "Chest" [ "Bottom of the Well" ] "Bottom of the Well" (\tracker -> (tracker |> canPlayZelda) && (tracker.kokiriSword || (tracker |> hasDekuSticks)))
    , Location "Bottom of the Well GS West Inner Room" "GS Token" [ "Bottom of the Well", "Skulltulas" ] "Bottom of the Well" (\tracker -> tracker.boomerang && (tracker |> canUseLensOfTruth) && (tracker.smallKeys.well >= 3))
    , Location "Bottom of the Well GS East Inner Room" "GS Token" [ "Bottom of the Well", "Skulltulas" ] "Bottom of the Well" (\tracker -> tracker.boomerang && (tracker |> canUseLensOfTruth) && (tracker.smallKeys.well >= 3))
    , Location "Bottom of the Well GS Like Like Cage" "GS Token" [ "Bottom of the Well", "Skulltulas" ] "Bottom of the Well" (\tracker -> tracker.boomerang && (tracker |> canUseLensOfTruth) && (tracker.smallKeys.well >= 3))

    -- Deku Tree
    , Location "Deku Tree Map Chest" "Chest" [ "Deku Tree" ] "Deku Tree" (\tracker -> True)
    , Location "Deku Tree Slingshot Room Side Chest" "Chest" [ "Deku Tree" ] "Deku Tree" (\tracker -> True)
    , Location "Deku Tree Slingshot Chest" "Chest" [ "Deku Tree" ] "Deku Tree" (\tracker -> True)
    , Location "Deku Tree Compass Chest" "Chest" [ "Deku Tree" ] "Deku Tree" (\tracker -> True)
    , Location "Deku Tree Compass Room Side Chest" "Chest" [ "Deku Tree" ] "Deku Tree" (\tracker -> True)
    , Location "Deku Tree Basement Chest" "Chest" [ "Deku Tree" ] "Deku Tree" (\tracker -> (tracker |> canBeAdult) || (tracker |> canChildAttack) || (tracker |> hasDekuNuts))
    , Location "Deku Tree GS Compass Room" "GS Token" [ "Deku Tree", "Skulltulas" ] "Deku Tree" (\tracker -> (tracker |> canBeAdult) || (tracker |> canChildAttack))
    , Location "Deku Tree GS Basement Vines" "GS Token" [ "Deku Tree", "Skulltulas" ] "Deku Tree" (\tracker -> (tracker |> canUseProjectile) || (tracker |> canUseDinsFire) || (tracker |> canBeAdult) || (tracker |> hasDekuSticks) || tracker.kokiriSword)
    , Location "Deku Tree GS Basement Gate" "GS Token" [ "Deku Tree", "Skulltulas" ] "Deku Tree" (\tracker -> (tracker |> canBeAdult) || (tracker |> canChildAttack))
    , Location "Deku Tree GS Basement Back Room" "GS Token" [ "Deku Tree", "Skulltulas" ] "Deku Tree" (\tracker -> (tracker |> hasFireSourceWithTorch) && (tracker |> canBlastOrSmash) && (tracker.boomerang || (tracker |> hasHookshot)))
    , Location "Deku Tree Queen Gohma Heart" "BossHeart" [ "Deku Tree" ] "Deku Tree" (\tracker -> (tracker |> canShieldBounce) && ((tracker |> canBeAdult) || tracker.kokiriSword || (tracker |> hasDekuSticks)))
    , Location "Queen Gohma" "Boss" [] "Deku Tree" (\tracker -> (tracker |> canShieldBounce) && ((tracker |> canBeAdult) || tracker.kokiriSword || (tracker |> hasDekuSticks)))

    -- Dodongo's Cavern
    , Location "Dodongos Cavern Map Chest" "Chest" [ "Dodongo's Cavern" ] "Dodongo's Cavern" (\tracker -> True)
    , Location "Dodongos Cavern Compass Chest" "Chest" [ "Dodongo's Cavern" ] "Dodongo's Cavern" (\tracker -> True)
    , Location "Dodongos Cavern Bomb Flower Platform Chest" "Chest" [ "Dodongo's Cavern" ] "Dodongo's Cavern" (\tracker -> True)
    , Location "Dodongos Cavern Bomb Bag Chest" "Chest" [ "Dodongo's Cavern" ] "Dodongo's Cavern" (\tracker -> True)
    , Location "Dodongos Cavern End of Bridge Chest" "Chest" [ "Dodongo's Cavern" ] "Dodongo's Cavern" canBlastOrSmash
    , Location "Dodongos Cavern Deku Scrub Side Room Near Dodongos" "NPC" [ "Dodongo's Cavern", "Deku Scrub" ] "Dodongo's Cavern" (\tracker -> (tracker |> canBeAdult) || (tracker |> hasSlingshot) || (tracker |> hasDekuSticks) || (tracker |> hasExplosives) || tracker.kokiriSword)
    , Location "Dodongos Cavern Deku Scrub Lobby" "NPC" [ "Dodongo's Cavern", "Deku Scrub" ] "Dodongo's Cavern" (\tracker -> True)
    , Location "Dodongos Cavern Deku Scrub Near Bomb Bag Left" "NPC" [ "Dodongo's Cavern", "Deku Scrub" ] "Dodongo's Cavern" (\tracker -> (tracker |> canBlastOrSmash) || ((tracker |> canBeAdult) && (tracker |> hasGoronBracer)))
    , Location "Dodongos Cavern Deku Scrub Near Bomb Bag Right" "NPC" [ "Dodongo's Cavern", "Deku Scrub" ] "Dodongo's Cavern" (\tracker -> (tracker |> canBlastOrSmash) || ((tracker |> canBeAdult) && (tracker |> hasGoronBracer)))
    , Location "Dodongos Cavern GS Side Room Near Lower Lizalfos" "GS Token" [ "Dodongo's Cavern", "Skulltulas" ] "Dodongo's Cavern" (\tracker -> (tracker |> hasExplosives) || (tracker |> canBeAdult) || (tracker |> hasSlingshot) || tracker.kokiriSword || tracker.boomerang)
    , Location "Dodongos Cavern GS Scarecrow" "GS Token" [ "Dodongo's Cavern", "Skulltulas" ] "Dodongo's Cavern" (\tracker -> (tracker |> canHitScarecrow) || (tracker |> hasLongshot) || (tracker |> canBeAdult) || (tracker |> canChildAttack))
    , Location "Dodongos Cavern GS Alcove Above Stairs" "GS Token" [ "Dodongo's Cavern", "Skulltulas" ] "Dodongo's Cavern" canGetFromFarAway
    , Location "Dodongos Cavern GS Vines Above Stairs" "GS Token" [ "Dodongo's Cavern", "Skulltulas" ] "Dodongo's Cavern" (\tracker -> (tracker |> hasExplosives) || (tracker |> hasGoronBracer) || (tracker |> canUseDinsFire) || (tracker |> hasBow) || (tracker |> hasLongshot))
    , Location "Dodongos Cavern GS Back Room" "GS Token" [ "Dodongo's Cavern", "Skulltulas" ] "Dodongo's Cavern" (\tracker -> True)
    , Location "Dodongos Cavern Boss Room Chest" "Chest" [ "Dodongo's Cavern" ] "Dodongo's Cavern" (\tracker -> True)
    , Location "Dodongos Cavern King Dodongo Heart" "BossHeart" [ "Dodongo's Cavern" ] "Dodongo's Cavern" (\tracker -> ((tracker |> hasBombs) || (tracker |> hasGoronBracer)) and ((tracker |> canBeAdult) || (tracker |> hasDekuNuts) || tracker.kokiriSword))
    , Location "Dodongos Cavern Gossip Stone" "HintStone" [] "Dodongo's Cavern" (\tracker -> True)
    , Location "King Dodongo" "Boss" [] "Dodongo's Cavern" (\tracker -> ((tracker |> hasBombs) || (tracker |> hasGoronBracer)) and ((tracker |> canBeAdult) || (tracker |> hasDekuNuts) || tracker.kokiriSword))

    -- Fire Temple
    , Location "Fire Temple Near Boss Chest" "Chest" [ "Fire Temple" ] "Fire Temple" hasGoronTunic
    , Location "Fire Temple Flare Dancer Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> (tracker |> hasHammer) && (tracker.smallKeys.fire >= 8))
    , Location "Fire Temple Boss Key Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> (tracker |> hasHammer) && (tracker.smallKeys.fire >= 8))
    , Location "Fire Temple Big Lava Room Lower Open Door Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> True)
    , Location "Fire Temple Big Lava Room Blocked Door Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> (tracker |> canBeAdult) && (tracker |> hasExplosives))
    , Location "Fire Temple Boulder Maze Lower Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> True)
    , Location "Fire Temple Boulder Maze Side Room Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> True)
    , Location "Fire Temple Map Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> (tracker.smallKeys.fire >= 6) || ((tracker.smallKeys.fire >= 5) && (tracker |> canBeAdult) && (tracker |> hasBow)))
    , Location "Fire Temple Boulder Maze Shortcut Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> (tracker.smallKeys.fire >= 6) && (tracker |> hasExplosives))
    , Location "Fire Temple Boulder Maze Upper Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> tracker.smallKeys.fire >= 6)
    , Location "Fire Temple Scarecrow Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> (tracker.smallKeys.fire >= 6) && ((tracker |> canHitScarecrow) || (tracker |> hasLongshot)))
    , Location "Fire Temple Compass Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> tracker.smallKeys.fire >= 7)
    , Location "Fire Temple Megaton Hammer Chest" "Chest" [ "Fire Temple" ] "Fire Temple" hasExplosives
    , Location "Fire Temple Highest Goron Chest" "Chest" [ "Fire Temple" ] "Fire Temple" (\tracker -> (tracker |> hasHammer) && ((tracker |> canPlayTime) || ((tracker |> hasHoverBoots) || (tracker |> hasExplosives))))
    , Location "Fire Temple GS Boss Key Loop" "GS Token" [ "Fire Temple", "Skulltulas" ] "Fire Temple" (\tracker -> (tracker.smallKeys.fire >= 7) && (tracker |> hasHammer))
    , Location "Fire Temple GS Song of Time Room" "GS Token" [ "Fire Temple", "Skulltulas" ] "Fire Temple" (\tracker -> (tracker |> canBeAdult) && (tracker |> canPlayTime))
    , Location "Fire Temple GS Boulder Maze" "GS Token" [ "Fire Temple", "Skulltulas" ] "Fire Temple" (\tracker -> (tracker.smallKeys.fire >= 4) && (tracker |> hasExplosives))
    , Location "Fire Temple GS Scarecrow Climb" "GS Token" [ "Fire Temple", "Skulltulas" ] "Fire Temple" (\tracker -> (tracker.smallKeys.fire >= 6) && ((tracker |> canHitScarecrow) || (tracker |> hasLongshot)))
    , Location "Fire Temple GS Scarecrow Top" "GS Token" [ "Fire Temple", "Skulltulas" ] "Fire Temple" (\tracker -> (tracker.smallKeys.fire >= 6) && ((tracker |> canHitScarecrow) || (tracker |> hasLongshot)))
    , Location "Fire Temple Volvagia Heart" "BossHeart" [ "Fire Temple" ] "Fire Temple" (\tracker -> (tracker |> hasGoronTunic) && (tracker |> hasHammer) && tracker.bossKeys.fire && ((tracker |> hasHoverBoots) || (tracker |> canPlayTime) || (tracker |> hasExplosives)))
    , Location "Volvagia" "Boss" [] "Fire Temple" (\tracker -> (tracker |> hasGoronTunic) && (tracker |> hasHammer) && tracker.bossKeys.fire && ((tracker |> hasHoverBoots) || (tracker |> canPlayTime) || (tracker |> hasExplosives)))

    -- Forest Temple
    , Location "Forest Temple First Room Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple First Stalfos Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Raised Island Courtyard Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Map Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Well Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Eye Switch Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Boss Key Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Floormaster Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Red Poe Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Bow Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Blue Poe Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Falling Ceiling Room Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Basement Chest" "Chest" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Forest Temple GS First Room" "GS Token" [ "Forest Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Forest Temple GS Lobby" "GS Token" [ "Forest Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Forest Temple GS Raised Island Courtyard" "GS Token" [ "Forest Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Forest Temple GS Level Island Courtyard" "GS Token" [ "Forest Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Forest Temple GS Basement" "GS Token" [ "Forest Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Forest Temple Phantom Ganon Heart" "BossHeart" [ "Forest Temple" ] "TODO" (\tracker -> True)
    , Location "Phantom Ganon" "Boss" [] "TODO" (\tracker -> True)

    -- Ganon's Castle
    , Location "Ganons Castle Forest Trial Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Water Trial Left Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Water Trial Right Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Shadow Trial Front Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Shadow Trial Golden Gauntlets Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Light Trial First Left Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Light Trial Second Left Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Light Trial Third Left Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Light Trial First Right Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Light Trial Second Right Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Light Trial Third Right Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Light Trial Invisible Enemies Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Light Trial Lullaby Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Spirit Trial Crystal Switch Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Spirit Trial Invisible Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Deku Scrub Left" "NPC" [ "Ganon's Castle", "Deku Scrub" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Deku Scrub Center-Left" "NPC" [ "Ganon's Castle", "Deku Scrub" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Deku Scrub Center-Right" "NPC" [ "Ganon's Castle", "Deku Scrub" ] "TODO" (\tracker -> True)
    , Location "Ganons Castle Deku Scrub Right" "NPC" [ "Ganon's Castle", "Deku Scrub" ] "TODO" (\tracker -> True)
    , Location "Ganon" "Event" [] "TODO" (\tracker -> True)
    , Location "OGC Great Fairy Reward" "Cutscene" [ "Ganon's Castle", "Market", "Fairies" ] "TODO" (\tracker -> True)
    , Location "OGC GS" "GS Token" [ "Ganon's Castle", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Ganons Tower Boss Key Chest" "Chest" [ "Ganon's Castle" ] "TODO" (\tracker -> True)

    -- Gerudo Training Grounds
    , Location "Gerudo Training Grounds Lobby Left Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Lobby Right Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Stalfos Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Before Heavy Block Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Heavy Block First Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Heavy Block Second Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Heavy Block Third Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Heavy Block Fourth Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Eye Statue Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Near Scarecrow Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Hammer Room Clear Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Hammer Room Switch Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Freestanding Key" "Collectable" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Maze Right Central Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Maze Right Side Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Underwater Silver Rupee Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Beamos Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Hidden Ceiling Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Maze Path First Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Maze Path Second Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Maze Path Third Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)
    , Location "Gerudo Training Grounds Maze Path Final Chest" "Chest" [ "Gerudo Training Grounds" ] "TODO" (\tracker -> True)

    -- Ice Cavern
    , Location "Ice Cavern Map Chest" "Chest" [ "Ice Cavern" ] "TODO" (\tracker -> True)
    , Location "Ice Cavern Compass Chest" "Chest" [ "Ice Cavern" ] "TODO" (\tracker -> True)
    , Location "Ice Cavern Freestanding PoH" "Collectable" [ "Ice Cavern" ] "TODO" (\tracker -> True)
    , Location "Ice Cavern Iron Boots Chest" "Chest" [ "Ice Cavern" ] "TODO" (\tracker -> True)
    , Location "Ice Cavern GS Spinning Scythe Room" "GS Token" [ "Ice Cavern", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Ice Cavern GS Heart Piece Room" "GS Token" [ "Ice Cavern", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Ice Cavern GS Push Block Room" "GS Token" [ "Ice Cavern", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Sheik in Ice Cavern" "Song" [ "Ice Cavern", "Songs" ] "TODO" (\tracker -> True)

    -- Jabu Jabu's Belly
    , Location "Jabu Jabus Belly Boomerang Chest" "Chest" [ "Jabu Jabu's Belly" ] "TODO" (\tracker -> True)
    , Location "Jabu Jabus Belly Map Chest" "Chest" [ "Jabu Jabu's Belly" ] "TODO" (\tracker -> True)
    , Location "Jabu Jabus Belly Compass Chest" "Chest" [ "Jabu Jabu's Belly" ] "TODO" (\tracker -> True)
    , Location "Jabu Jabus Belly Deku Scrub" "NPC" [ "Jabu Jabu's Belly", "Deku Scrub" ] "TODO" (\tracker -> True)
    , Location "Jabu Jabus Belly GS Water Switch Room" "GS Token" [ "Jabu Jabu's Belly", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Jabu Jabus Belly GS Lobby Basement Lower" "GS Token" [ "Jabu Jabu's Belly", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Jabu Jabus Belly GS Lobby Basement Upper" "GS Token" [ "Jabu Jabu's Belly", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Jabu Jabus Belly GS Near Boss" "GS Token" [ "Jabu Jabu's Belly", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Jabu Jabus Belly Barinade Heart" "BossHeart" [ "Jabu Jabu's Belly" ] "TODO" (\tracker -> True)
    , Location "Barinade" "Boss" [] "TODO" (\tracker -> True)

    -- Shadow Temple
    , Location "Shadow Temple Map Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Hover Boots Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Compass Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Early Silver Rupee Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Invisible Blades Visible Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Invisible Blades Invisible Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Falling Spikes Lower Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Falling Spikes Upper Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Falling Spikes Switch Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Invisible Spikes Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Freestanding Key" "Collectable" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Wind Hint Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple After Wind Enemy Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple After Wind Hidden Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Spike Walls Left Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Boss Key Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Invisible Floormaster Chest" "Chest" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple GS Like Like Room" "GS Token" [ "Shadow Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple GS Falling Spikes Room" "GS Token" [ "Shadow Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple GS Single Giant Pot" "GS Token" [ "Shadow Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple GS Near Ship" "GS Token" [ "Shadow Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple GS Triple Giant Pot" "GS Token" [ "Shadow Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Shadow Temple Bongo Bongo Heart" "BossHeart" [ "Shadow Temple" ] "TODO" (\tracker -> True)
    , Location "Bongo Bongo" "Boss" [] "TODO" (\tracker -> True)

    -- Spirit Temple
    , Location "Spirit Temple Child Bridge Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Child Early Torches Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Child Climb North Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Child Climb East Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Map Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Sun Block Room Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Silver Gauntlets Chest" "Chest" [ "Spirit Temple", "Desert Colossus" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Compass Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Early Adult Right Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple First Mirror Left Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple First Mirror Right Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Statue Room Northeast Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Statue Room Hand Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Near Four Armos Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Hallway Right Invisible Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Hallway Left Invisible Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Mirror Shield Chest" "Chest" [ "Spirit Temple", "Desert Colossus" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Boss Key Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Topmost Chest" "Chest" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple GS Metal Fence" "GS Token" [ "Spirit Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple GS Sun on Floor Room" "GS Token" [ "Spirit Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple GS Hall After Sun Block Room" "GS Token" [ "Spirit Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple GS Lobby" "GS Token" [ "Spirit Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple GS Boulder Room" "GS Token" [ "Spirit Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Spirit Temple Twinrova Heart" "BossHeart" [ "Spirit Temple" ] "TODO" (\tracker -> True)
    , Location "Twinrova" "Boss" [] "TODO" (\tracker -> True)

    -- Water Temple
    , Location "Water Temple Compass Chest" "Chest" [ "Water Temple" ] "TODO" (\tracker -> True)
    , Location "Water Temple Map Chest" "Chest" [ "Water Temple" ] "TODO" (\tracker -> True)
    , Location "Water Temple Cracked Wall Chest" "Chest" [ "Water Temple" ] "TODO" (\tracker -> True)
    , Location "Water Temple Torches Chest" "Chest" [ "Water Temple" ] "TODO" (\tracker -> True)
    , Location "Water Temple Boss Key Chest" "Chest" [ "Water Temple" ] "TODO" (\tracker -> True)
    , Location "Water Temple Central Pillar Chest" "Chest" [ "Water Temple" ] "TODO" (\tracker -> True)
    , Location "Water Temple Central Bow Target Chest" "Chest" [ "Water Temple" ] "TODO" (\tracker -> True)
    , Location "Water Temple Longshot Chest" "Chest" [ "Water Temple" ] "TODO" (\tracker -> True)
    , Location "Water Temple River Chest" "Chest" [ "Water Temple" ] "TODO" (\tracker -> True)
    , Location "Water Temple Dragon Chest" "Chest" [ "Water Temple" ] "TODO" (\tracker -> True)
    , Location "Water Temple GS Behind Gate" "GS Token" [ "Water Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Water Temple GS Near Boss Key Chest" "GS Token" [ "Water Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Water Temple GS Central Pillar" "GS Token" [ "Water Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Water Temple GS Falling Platform Room" "GS Token" [ "Water Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Water Temple GS River" "GS Token" [ "Water Temple", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Water Temple Morpha Heart" "BossHeart" [ "Water Temple" ] "TODO" (\tracker -> True)
    , Location "Morpha" "Boss" [] "TODO" (\tracker -> True)

    -- Overworld
    -- Kokiri Forest (KF)
    , Location "KF Midos Top Left Chest" "Chest" [ "Kokiri Forest", "Forest" ] "TODO" (\tracker -> True)
    , Location "KF Midos Top Right Chest" "Chest" [ "Kokiri Forest", "Forest" ] "TODO" (\tracker -> True)
    , Location "KF Midos Bottom Left Chest" "Chest" [ "Kokiri Forest", "Forest" ] "TODO" (\tracker -> True)
    , Location "KF Midos Bottom Right Chest" "Chest" [ "Kokiri Forest", "Forest" ] "TODO" (\tracker -> True)
    , Location "KF Kokiri Sword Chest" "Chest" [ "Kokiri Forest", "Forest" ] "TODO" (\tracker -> True)
    , Location "KF Storms Grotto Chest" "Chest" [ "Kokiri Forest", "Forest", "Grottos" ] "TODO" (\tracker -> True)
    , Location "KF Links House Cow" "NPC" [ "KF Links House", "Forest", "Cow", "Minigames" ] "TODO" (\tracker -> True)
    , Location "KF GS Know It All House" "GS Token" [ "Kokiri Forest", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "KF GS Bean Patch" "GS Token" [ "Kokiri Forest", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "KF GS House of Twins" "GS Token" [ "Kokiri Forest", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "KF Shop Item 1" "Shop" [ "Kokiri Forest", "Forest", "Shops" ] "TODO" (\tracker -> True)
    , Location "KF Shop Item 2" "Shop" [ "Kokiri Forest", "Forest", "Shops" ] "TODO" (\tracker -> True)
    , Location "KF Shop Item 3" "Shop" [ "Kokiri Forest", "Forest", "Shops" ] "TODO" (\tracker -> True)
    , Location "KF Shop Item 4" "Shop" [ "Kokiri Forest", "Forest", "Shops" ] "TODO" (\tracker -> True)
    , Location "KF Shop Item 5" "Shop" [ "Kokiri Forest", "Forest", "Shops" ] "TODO" (\tracker -> True)
    , Location "KF Shop Item 6" "Shop" [ "Kokiri Forest", "Forest", "Shops" ] "TODO" (\tracker -> True)
    , Location "KF Shop Item 7" "Shop" [ "Kokiri Forest", "Forest", "Shops" ] "TODO" (\tracker -> True)
    , Location "KF Shop Item 8" "Shop" [ "Kokiri Forest", "Forest", "Shops" ] "TODO" (\tracker -> True)
    , Location "KF Deku Tree Gossip Stone (Left)" "HintStone" [] "TODO" (\tracker -> True)
    , Location "KF Deku Tree Gossip Stone (Right)" "HintStone" [] "TODO" (\tracker -> True)
    , Location "KF Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "KF Storms Grotto Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Lost Woods (LW)
    , Location "LW Gift from Saria" "Cutscene" [ "Lost Woods", "Forest" ] "TODO" (\tracker -> True)
    , Location "LW Ocarina Memory Game" "NPC" [ "Lost Woods", "Forest", "Minigames" ] "TODO" (\tracker -> True)
    , Location "LW Target in Woods" "NPC" [ "Lost Woods", "Forest" ] "TODO" (\tracker -> True)
    , Location "LW Near Shortcuts Grotto Chest" "Chest" [ "Lost Woods", "Forest", "Grottos" ] "TODO" (\tracker -> True)
    , Location "Deku Theater Skull Mask" "NPC" [ "Lost Woods", "Forest", "Grottos" ] "TODO" (\tracker -> True)
    , Location "Deku Theater Mask of Truth" "NPC" [ "Lost Woods", "Forest", "Need Spiritual Stones", "Grottos" ] "TODO" (\tracker -> True)
    , Location "LW Skull Kid" "NPC" [ "Lost Woods", "Forest" ] "TODO" (\tracker -> True)
    , Location "LW Deku Scrub Near Bridge" "NPC" [ "Lost Woods", "Forest", "Deku Scrub", "Deku Scrub Upgrades" ] "TODO" (\tracker -> True)
    , Location "LW Deku Scrub Near Deku Theater Left" "NPC" [ "Lost Woods", "Forest", "Deku Scrub" ] "TODO" (\tracker -> True)
    , Location "LW Deku Scrub Near Deku Theater Right" "NPC" [ "Lost Woods", "Forest", "Deku Scrub" ] "TODO" (\tracker -> True)
    , Location "LW Deku Scrub Grotto Front" "GrottoNPC" [ "Lost Woods", "Forest", "Deku Scrub", "Deku Scrub Upgrades", "Grottos" ] "TODO" (\tracker -> True)
    , Location "LW Deku Scrub Grotto Rear" "GrottoNPC" [ "Lost Woods", "Forest", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "LW GS Bean Patch Near Bridge" "GS Token" [ "Lost Woods", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "LW GS Bean Patch Near Theater" "GS Token" [ "Lost Woods", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "LW GS Above Theater" "GS Token" [ "Lost Woods", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "LW Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "LW Near Shortcuts Grotto Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Hyrule Field (HF)
    , Location "HF Ocarina of Time Item" "NPC" [ "Hyrule Field", "Need Spiritual Stones" ] "TODO" (\tracker -> True)
    , Location "HF Near Market Grotto Chest" "Chest" [ "Hyrule Field", "Grottos" ] "TODO" (\tracker -> True)
    , Location "HF Tektite Grotto Freestanding PoH" "Collectable" [ "Hyrule Field", "Grottos" ] "TODO" (\tracker -> True)
    , Location "HF Southeast Grotto Chest" "Chest" [ "Hyrule Field", "Grottos" ] "TODO" (\tracker -> True)
    , Location "HF Open Grotto Chest" "Chest" [ "Hyrule Field", "Grottos" ] "TODO" (\tracker -> True)
    , Location "HF Deku Scrub Grotto" "GrottoNPC" [ "Hyrule Field", "Deku Scrub", "Deku Scrub Upgrades", "Grottos" ] "TODO" (\tracker -> True)
    , Location "HF Cow Grotto Cow" "NPC" [ "Hyrule Field", "Cow", "Grottos" ] "TODO" (\tracker -> True)
    , Location "HF GS Cow Grotto" "GS Token" [ "Hyrule Field", "Skulltulas", "Grottos" ] "TODO" (\tracker -> True)
    , Location "HF GS Near Kak Grotto" "GS Token" [ "Hyrule Field", "Skulltulas", "Grottos" ] "TODO" (\tracker -> True)
    , Location "HF Near Market Grotto Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "HF Southeast Grotto Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "HF Open Grotto Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "HF Cow Grotto Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "Song from Ocarina of Time" "Song" [ "Hyrule Field", "Songs", "Need Spiritual Stones" ] "TODO" (\tracker -> True)

    -- Kakariko Village (KAK)
    , Location "Kak Anju as Child" "NPC" [ "Kakariko Village", "Kakariko", "Minigames" ] "TODO" (\tracker -> True)
    , Location "Kak Anju as Adult" "NPC" [ "Kakariko Village", "Kakariko" ] "TODO" (\tracker -> True)
    , Location "Kak Impas House Freestanding PoH" "Collectable" [ "Kakariko Village", "Kakariko" ] "TODO" (\tracker -> True)
    , Location "Kak Windmill Freestanding PoH" "Collectable" [ "Kakariko Village", "Kakariko" ] "TODO" (\tracker -> True)
    , Location "Kak Man on Roof" "NPC" [ "Kakariko Village", "Kakariko" ] "TODO" (\tracker -> True)
    , Location "Kak Open Grotto Chest" "Chest" [ "Kakariko Village", "Kakariko", "Grottos" ] "TODO" (\tracker -> True)
    , Location "Kak Redead Grotto Chest" "Chest" [ "Kakariko Village", "Kakariko", "Grottos" ] "TODO" (\tracker -> True)
    , Location "Kak Shooting Gallery Reward" "NPC" [ "Kakariko Village", "Kakariko", "Minigames" ] "TODO" (\tracker -> True)
    , Location "Kak 10 Gold Skulltula Reward" "NPC" [ "Kakariko Village", "Kakariko", "Skulltula House" ] "TODO" (\tracker -> True)
    , Location "Kak 20 Gold Skulltula Reward" "NPC" [ "Kakariko Village", "Kakariko", "Skulltula House" ] "TODO" (\tracker -> True)
    , Location "Kak 30 Gold Skulltula Reward" "NPC" [ "Kakariko Village", "Kakariko", "Skulltula House" ] "TODO" (\tracker -> True)
    , Location "Kak 40 Gold Skulltula Reward" "NPC" [ "Kakariko Village", "Kakariko", "Skulltula House" ] "TODO" (\tracker -> True)
    , Location "Kak 50 Gold Skulltula Reward" "NPC" [ "Kakariko Village", "Kakariko", "Skulltula House" ] "TODO" (\tracker -> True)
    , Location "Kak Impas House Cow" "NPC" [ "Kakariko Village", "Kakariko", "Cow" ] "TODO" (\tracker -> True)
    , Location "Kak GS Tree" "GS Token" [ "Kakariko Village", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Kak GS Guards House" "GS Token" [ "Kakariko Village", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Kak GS Watchtower" "GS Token" [ "Kakariko Village", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Kak GS Skulltula House" "GS Token" [ "Kakariko Village", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Kak GS House Under Construction" "GS Token" [ "Kakariko Village", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Kak GS Above Impas House" "GS Token" [ "Kakariko Village", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Kak Bazaar Item 1" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Bazaar Item 2" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Bazaar Item 3" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Bazaar Item 4" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Bazaar Item 5" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Bazaar Item 6" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Bazaar Item 7" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Bazaar Item 8" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Potion Shop Item 1" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Potion Shop Item 2" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Potion Shop Item 3" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Potion Shop Item 4" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Potion Shop Item 5" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Potion Shop Item 6" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Potion Shop Item 7" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Kak Potion Shop Item 8" "Shop" [ "Kakariko Village", "Kakariko", "Shops" ] "TODO" (\tracker -> True)
    , Location "Song from Windmill" "Song" [ "Kakariko Village", "Kakariko", "Songs" ] "TODO" (\tracker -> True)
    , Location "Sheik in Kakariko" "Song" [ "Kakariko Village", "Kakariko", "Songs" ] "TODO" (\tracker -> True)
    , Location "Kak Open Grotto Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Hyrule Castle (HC) + Market
    , Location "HC Malon Egg" "NPC" [ "Hyrule Castle", "Market" ] "TODO" (\tracker -> True)
    , Location "HC Zeldas Letter" "NPC" [ "Hyrule Castle", "Market" ] "TODO" (\tracker -> True)
    , Location "HC Great Fairy Reward" "Cutscene" [ "Hyrule Castle", "Market", "Fairies" ] "TODO" (\tracker -> True)
    , Location "HC GS Tree" "GS Token" [ "Hyrule Castle", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "HC GS Storms Grotto" "GS Token" [ "Hyrule Castle", "Skulltulas", "Grottos" ] "TODO" (\tracker -> True)
    , Location "HC Malon Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "HC Rock Wall Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "HC Storms Grotto Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "Song from Impa" "Song" [ "Hyrule Castle", "Market", "Songs" ] "TODO" (\tracker -> True)
    , Location "Market 10 Big Poes" "NPC" [ "Hyrule Castle" ] "TODO" (\tracker -> True)
    , Location "Sheik at Temple" "Song" [ "Temple of Time", "Market", "Songs" ] "TODO" (\tracker -> True)
    , Location "Market Shooting Gallery Reward" "NPC" [ "Market", "Minigames" ] "TODO" (\tracker -> True)
    , Location "Market Bombchu Bowling First Prize" "NPC" [ "Market", "Minigames" ] "TODO" (\tracker -> True)
    , Location "Market Bombchu Bowling Second Prize" "NPC" [ "Market", "Minigames" ] "TODO" (\tracker -> True)
    , Location "Market Bombchu Bowling Bombchus" "NPC" [ "Market", "Minigames" ] "TODO" (\tracker -> True)
    , Location "Market Lost Dog" "NPC" [ "Market" ] "TODO" (\tracker -> True)
    , Location "Market Treasure Chest Game Reward" "Chest" [ "Market", "Minigames" ] "TODO" (\tracker -> True)
    , Location "Market GS Guard House" "GS Token" [ "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Market Bazaar Item 1" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bazaar Item 2" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bazaar Item 3" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bazaar Item 4" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bazaar Item 5" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bazaar Item 6" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bazaar Item 7" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bazaar Item 8" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Potion Shop Item 1" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Potion Shop Item 2" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Potion Shop Item 3" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Potion Shop Item 4" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Potion Shop Item 5" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Potion Shop Item 6" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Potion Shop Item 7" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Potion Shop Item 8" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bombchu Shop Item 1" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bombchu Shop Item 2" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bombchu Shop Item 3" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bombchu Shop Item 4" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bombchu Shop Item 5" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bombchu Shop Item 6" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bombchu Shop Item 7" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "Market Bombchu Shop Item 8" "Shop" [ "Market", "Shops" ] "TODO" (\tracker -> True)
    , Location "ToT Light Arrows Cutscene" "Cutscene" [ "Temple of Time", "Market" ] "TODO" (\tracker -> True)
    , Location "ToT Gossip Stone (Left)" "HintStone" [] "TODO" (\tracker -> True)
    , Location "ToT Gossip Stone (Left-Center)" "HintStone" [] "TODO" (\tracker -> True)
    , Location "ToT Gossip Stone (Right)" "HintStone" [] "TODO" (\tracker -> True)
    , Location "ToT Gossip Stone (Right-Center)" "HintStone" [] "TODO" (\tracker -> True)

    -- Lon Lon Ranch (LLR)
    , Location "Song from Malon" "Song" [ "Lon Lon Ranch", "Songs" ] "TODO" (\tracker -> True)
    , Location "LLR Talons Chickens" "NPC" [ "Lon Lon Ranch", "Kakariko", "Minigames" ] "TODO" (\tracker -> True)
    , Location "LLR Freestanding PoH" "Collectable" [ "Lon Lon Ranch" ] "TODO" (\tracker -> True)
    , Location "LLR Deku Scrub Grotto Left" "GrottoNPC" [ "Lon Lon Ranch", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "LLR Deku Scrub Grotto Center" "GrottoNPC" [ "Lon Lon Ranch", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "LLR Deku Scrub Grotto Right" "GrottoNPC" [ "Lon Lon Ranch", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "LLR Stables Left Cow" "NPC" [ "Lon Lon Ranch", "Cow" ] "TODO" (\tracker -> True)
    , Location "LLR Stables Right Cow" "NPC" [ "Lon Lon Ranch", "Cow" ] "TODO" (\tracker -> True)
    , Location "LLR Tower Left Cow" "NPC" [ "Lon Lon Ranch", "Cow" ] "TODO" (\tracker -> True)
    , Location "LLR Tower Right Cow" "NPC" [ "Lon Lon Ranch", "Cow" ] "TODO" (\tracker -> True)
    , Location "LLR GS House Window" "GS Token" [ "Lon Lon Ranch", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "LLR GS Tree" "GS Token" [ "Lon Lon Ranch", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "LLR GS Rain Shed" "GS Token" [ "Lon Lon Ranch", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "LLR GS Back Wall" "GS Token" [ "Lon Lon Ranch", "Skulltulas" ] "TODO" (\tracker -> True)

    -- Graveyard
    , Location "Song from Composers Grave" "Song" [ "Graveyard", "Kakariko", "Songs" ] "TODO" (\tracker -> True)
    , Location "Graveyard Shield Grave Chest" "Chest" [ "Graveyard", "Kakariko" ] "TODO" (\tracker -> True)
    , Location "Graveyard Heart Piece Grave Chest" "Chest" [ "Graveyard", "Kakariko" ] "TODO" (\tracker -> True)
    , Location "Graveyard Composers Grave Chest" "Chest" [ "Graveyard", "Kakariko" ] "TODO" (\tracker -> True)
    , Location "Graveyard Freestanding PoH" "Collectable" [ "Graveyard", "Kakariko" ] "TODO" (\tracker -> True)
    , Location "Graveyard Dampe Gravedigging Tour" "Collectable" [ "Graveyard", "Kakariko" ] "TODO" (\tracker -> True)
    , Location "Graveyard Hookshot Chest" "Chest" [ "Graveyard", "Kakariko" ] "TODO" (\tracker -> True)
    , Location "Graveyard Dampe Race Freestanding PoH" "Collectable" [ "Graveyard", "Kakariko", "Minigames" ] "TODO" (\tracker -> True)
    , Location "Graveyard GS Bean Patch" "GS Token" [ "Graveyard", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Graveyard GS Wall" "GS Token" [ "Graveyard", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Graveyard Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Zora's River (ZR)
    , Location "ZR Magic Bean Salesman" "NPC" [ "Zora's River" ] "TODO" (\tracker -> True)
    , Location "ZR Open Grotto Chest" "Chest" [ "Zora's River", "Grottos" ] "TODO" (\tracker -> True)
    , Location "ZR Frogs in the Rain" "NPC" [ "Zora's River", "Minigames" ] "TODO" (\tracker -> True)
    , Location "ZR Frogs Ocarina Game" "NPC" [ "Zora's River" ] "TODO" (\tracker -> True)
    , Location "ZR Near Open Grotto Freestanding PoH" "Collectable" [ "Zora's River" ] "TODO" (\tracker -> True)
    , Location "ZR Near Domain Freestanding PoH" "Collectable" [ "Zora's River" ] "TODO" (\tracker -> True)
    , Location "ZR Deku Scrub Grotto Front" "GrottoNPC" [ "Zora's River", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "ZR Deku Scrub Grotto Rear" "GrottoNPC" [ "Zora's River", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "ZR GS Tree" "GS Token" [ "Zora's River", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "ZR GS Ladder" "GS Token" [ "Zora's River", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "ZR GS Near Raised Grottos" "GS Token" [ "Zora's River", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "ZR GS Above Bridge" "GS Token" [ "Zora's River", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "ZR Near Grottos Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "ZR Near Domain Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "ZR Open Grotto Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Zora's Domain (ZD)
    , Location "ZD Diving Minigame" "NPC" [ "Zora's Domain", "Minigames" ] "TODO" (\tracker -> True)
    , Location "ZD Chest" "Chest" [ "Zora's Domain" ] "TODO" (\tracker -> True)
    , Location "ZD King Zora Thawed" "NPC" [ "Zora's Domain" ] "TODO" (\tracker -> True)
    , Location "ZD GS Frozen Waterfall" "GS Token" [ "Zora's Domain", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "ZD Shop Item 1" "Shop" [ "Zora's Domain", "Shops" ] "TODO" (\tracker -> True)
    , Location "ZD Shop Item 2" "Shop" [ "Zora's Domain", "Shops" ] "TODO" (\tracker -> True)
    , Location "ZD Shop Item 3" "Shop" [ "Zora's Domain", "Shops" ] "TODO" (\tracker -> True)
    , Location "ZD Shop Item 4" "Shop" [ "Zora's Domain", "Shops" ] "TODO" (\tracker -> True)
    , Location "ZD Shop Item 5" "Shop" [ "Zora's Domain", "Shops" ] "TODO" (\tracker -> True)
    , Location "ZD Shop Item 6" "Shop" [ "Zora's Domain", "Shops" ] "TODO" (\tracker -> True)
    , Location "ZD Shop Item 7" "Shop" [ "Zora's Domain", "Shops" ] "TODO" (\tracker -> True)
    , Location "ZD Shop Item 8" "Shop" [ "Zora's Domain", "Shops" ] "TODO" (\tracker -> True)
    , Location "ZD Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Zora's Fountain (ZF)
    , Location "ZF Great Fairy Reward" "Cutscene" [ "Zora's Fountain", "Fairies" ] "TODO" (\tracker -> True)
    , Location "ZF Iceberg Freestanding PoH" "Collectable" [ "Zora's Fountain" ] "TODO" (\tracker -> True)
    , Location "ZF Bottom Freestanding PoH" "Collectable" [ "Zora's Fountain" ] "TODO" (\tracker -> True)
    , Location "ZF GS Above the Log" "GS Token" [ "Zora's Fountain", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "ZF GS Tree" "GS Token" [ "Zora's Fountain", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "ZF GS Hidden Cave" "GS Token" [ "Zora's Fountain", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "ZF Fairy Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "ZF Jabu Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Sacred Forest Meadow (SFM)
    , Location "Song from Saria" "Song" [ "Sacred Forest Meadow", "Forest", "Songs" ] "TODO" (\tracker -> True)
    , Location "Sheik in Forest" "Song" [ "Sacred Forest Meadow", "Forest", "Songs" ] "TODO" (\tracker -> True)
    , Location "SFM Wolfos Grotto Chest" "Chest" [ "Sacred Forest Meadow", "Forest", "Grottos" ] "TODO" (\tracker -> True)
    , Location "SFM Deku Scrub Grotto Front" "GrottoNPC" [ "Sacred Forest Meadow", "Forest", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "SFM Deku Scrub Grotto Rear" "GrottoNPC" [ "Sacred Forest Meadow", "Forest", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "SFM GS" "GS Token" [ "Sacred Forest Meadow", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "SFM Maze Gossip Stone (Lower)" "HintStone" [] "TODO" (\tracker -> True)
    , Location "SFM Maze Gossip Stone (Upper)" "HintStone" [] "TODO" (\tracker -> True)
    , Location "SFM Saria Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Death Mountain Trail (DMT)
    , Location "DMT Freestanding PoH" "Collectable" [ "Death Mountain Trail", "Death Mountain" ] "TODO" (\tracker -> True)
    , Location "DMT Chest" "Chest" [ "Death Mountain Trail", "Death Mountain" ] "TODO" (\tracker -> True)
    , Location "DMT Storms Grotto Chest" "Chest" [ "Death Mountain Trail", "Death Mountain", "Grottos" ] "TODO" (\tracker -> True)
    , Location "DMT Great Fairy Reward" "Cutscene" [ "Death Mountain Trail", "Death Mountain", "Fairies" ] "TODO" (\tracker -> True)
    , Location "DMT Biggoron" "NPC" [ "Death Mountain Trail", "Death Mountain" ] "TODO" (\tracker -> True)
    , Location "DMT Cow Grotto Cow" "NPC" [ "Death Mountain Trail", "Death Mountain", "Cow", "Grottos" ] "TODO" (\tracker -> True)
    , Location "DMT GS Near Kak" "GS Token" [ "Death Mountain Trail", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "DMT GS Bean Patch" "GS Token" [ "Death Mountain Trail", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "DMT GS Above Dodongos Cavern" "GS Token" [ "Death Mountain Trail", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "DMT GS Falling Rocks Path" "GS Token" [ "Death Mountain Trail", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "DMT Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "DMT Storms Grotto Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Goron City (GC)
    , Location "GC Darunias Joy" "NPC" [ "Goron City" ] "TODO" (\tracker -> True)
    , Location "GC Pot Freestanding PoH" "Collectable" [ "Goron City", "Goron City" ] "TODO" (\tracker -> True)
    , Location "GC Rolling Goron as Child" "NPC" [ "Goron City" ] "TODO" (\tracker -> True)
    , Location "GC Rolling Goron as Adult" "NPC" [ "Goron City" ] "TODO" (\tracker -> True)
    , Location "GC Medigoron" "NPC" [ "Goron City" ] "TODO" (\tracker -> True)
    , Location "GC Maze Left Chest" "Chest" [ "Goron City" ] "TODO" (\tracker -> True)
    , Location "GC Maze Right Chest" "Chest" [ "Goron City" ] "TODO" (\tracker -> True)
    , Location "GC Maze Center Chest" "Chest" [ "Goron City" ] "TODO" (\tracker -> True)
    , Location "GC Deku Scrub Grotto Left" "GrottoNPC" [ "Goron City", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "GC Deku Scrub Grotto Center" "GrottoNPC" [ "Goron City", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "GC Deku Scrub Grotto Right" "GrottoNPC" [ "Goron City", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "GC GS Center Platform" "GS Token" [ "Goron City", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "GC GS Boulder Maze" "GS Token" [ "Goron City", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "GC Shop Item 1" "Shop" [ "Goron City", "Shops" ] "TODO" (\tracker -> True)
    , Location "GC Shop Item 2" "Shop" [ "Goron City", "Shops" ] "TODO" (\tracker -> True)
    , Location "GC Shop Item 3" "Shop" [ "Goron City", "Shops" ] "TODO" (\tracker -> True)
    , Location "GC Shop Item 4" "Shop" [ "Goron City", "Shops" ] "TODO" (\tracker -> True)
    , Location "GC Shop Item 5" "Shop" [ "Goron City", "Shops" ] "TODO" (\tracker -> True)
    , Location "GC Shop Item 6" "Shop" [ "Goron City", "Shops" ] "TODO" (\tracker -> True)
    , Location "GC Shop Item 7" "Shop" [ "Goron City", "Shops" ] "TODO" (\tracker -> True)
    , Location "GC Shop Item 8" "Shop" [ "Goron City", "Shops" ] "TODO" (\tracker -> True)
    , Location "GC Maze Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "GC Medigoron Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Death Mountain Crater (DMC)
    , Location "Sheik in Crater" "Song" [ "Death Mountain Crater", "Death Mountain", "Songs" ] "TODO" (\tracker -> True)
    , Location "DMC Volcano Freestanding PoH" "Collectable" [ "Death Mountain Crater", "Death Mountain" ] "TODO" (\tracker -> True)
    , Location "DMC Wall Freestanding PoH" "Collectable" [ "Death Mountain Crater", "Death Mountain" ] "TODO" (\tracker -> True)
    , Location "DMC Upper Grotto Chest" "Chest" [ "Death Mountain Crater", "Death Mountain", "Grottos" ] "TODO" (\tracker -> True)
    , Location "DMC Great Fairy Reward" "Cutscene" [ "Death Mountain Crater", "Death Mountain", "Fairies" ] "TODO" (\tracker -> True)
    , Location "DMC Deku Scrub" "NPC" [ "Death Mountain Crater", "Death Mountain", "Deku Scrub" ] "TODO" (\tracker -> True)
    , Location "DMC Deku Scrub Grotto Left" "GrottoNPC" [ "Death Mountain Crater", "Death Mountain", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "DMC Deku Scrub Grotto Center" "GrottoNPC" [ "Death Mountain Crater", "Death Mountain", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "DMC Deku Scrub Grotto Right" "GrottoNPC" [ "Death Mountain Crater", "Death Mountain", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "DMC GS Crate" "GS Token" [ "Death Mountain Crater", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "DMC GS Bean Patch" "GS Token" [ "Death Mountain Crater", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "DMC Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "DMC Upper Grotto Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Lake Hylia (LH)
    , Location "LH Underwater Item" "NPC" [ "Lake Hylia" ] "TODO" (\tracker -> True)
    , Location "LH Child Fishing" "NPC" [ "Lake Hylia", "Minigames" ] "TODO" (\tracker -> True)
    , Location "LH Adult Fishing" "NPC" [ "Lake Hylia", "Minigames" ] "TODO" (\tracker -> True)
    , Location "LH Lab Dive" "NPC" [ "Lake Hylia" ] "TODO" (\tracker -> True)
    , Location "LH Freestanding PoH" "Collectable" [ "Lake Hylia" ] "TODO" (\tracker -> True)
    , Location "LH Sun" "NPC" [ "Lake Hylia" ] "TODO" (\tracker -> True)
    , Location "LH Deku Scrub Grotto Left" "GrottoNPC" [ "Lake Hylia", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "LH Deku Scrub Grotto Center" "GrottoNPC" [ "Lake Hylia", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "LH Deku Scrub Grotto Right" "GrottoNPC" [ "Lake Hylia", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "LH GS Bean Patch" "GS Token" [ "Lake Hylia", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "LH GS Lab Wall" "GS Token" [ "Lake Hylia", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "LH GS Small Island" "GS Token" [ "Lake Hylia", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "LH GS Lab Crate" "GS Token" [ "Lake Hylia", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "LH GS Tree" "GS Token" [ "Lake Hylia", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "LH Lab Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)
    , Location "LH Gossip Stone (Southeast)" "HintStone" [] "TODO" (\tracker -> True)
    , Location "LH Gossip Stone (Southwest)" "HintStone" [] "TODO" (\tracker -> True)

    -- Gerudo Valley (GV)
    , Location "GV Crate Freestanding PoH" "Collectable" [ "Gerudo Valley", "Gerudo" ] "TODO" (\tracker -> True)
    , Location "GV Waterfall Freestanding PoH" "Collectable" [ "Gerudo Valley", "Gerudo" ] "TODO" (\tracker -> True)
    , Location "GV Chest" "Chest" [ "Gerudo Valley", "Gerudo" ] "TODO" (\tracker -> True)
    , Location "GV Deku Scrub Grotto Front" "GrottoNPC" [ "Gerudo Valley", "Gerudo", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "GV Deku Scrub Grotto Rear" "GrottoNPC" [ "Gerudo Valley", "Gerudo", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "GV Cow" "NPC" [ "Gerudo Valley", "Gerudo", "Cow" ] "TODO" (\tracker -> True)
    , Location "GV GS Small Bridge" "GS Token" [ "Gerudo Valley", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "GV GS Bean Patch" "GS Token" [ "Gerudo Valley", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "GV GS Behind Tent" "GS Token" [ "Gerudo Valley", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "GV GS Pillar" "GS Token" [ "Gerudo Valley", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "GV Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Gerudo's Fortress (GF)
    , Location "GF North F1 Carpenter" "Collectable" [ "Gerudo's Fortress", "Gerudo" ] "TODO" (\tracker -> True)
    , Location "GF North F2 Carpenter" "Collectable" [ "Gerudo's Fortress", "Gerudo" ] "TODO" (\tracker -> True)
    , Location "GF South F1 Carpenter" "Collectable" [ "Gerudo's Fortress", "Gerudo" ] "TODO" (\tracker -> True)
    , Location "GF South F2 Carpenter" "Collectable" [ "Gerudo's Fortress", "Gerudo" ] "TODO" (\tracker -> True)
    , Location "GF Gerudo Membership Card" "NPC" [ "Gerudo's Fortress", "Gerudo" ] "TODO" (\tracker -> True)
    , Location "GF Chest" "Chest" [ "Gerudo's Fortress", "Gerudo" ] "TODO" (\tracker -> True)
    , Location "GF HBA 1000 Points" "NPC" [ "Gerudo's Fortress", "Gerudo", "Minigames" ] "TODO" (\tracker -> True)
    , Location "GF HBA 1500 Points" "NPC" [ "Gerudo's Fortress", "Gerudo", "Minigames" ] "TODO" (\tracker -> True)
    , Location "GF GS Top Floor" "GS Token" [ "Gerudo's Fortress", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "GF GS Archery Range" "GS Token" [ "Gerudo's Fortress", "Skulltulas" ] "TODO" (\tracker -> True)

    -- Desert Colossus
    , Location "Sheik at Colossus" "Song" [ "Desert Colossus", "Songs" ] "TODO" (\tracker -> True)
    , Location "Colossus Great Fairy Reward" "Cutscene" [ "Desert Colossus", "Fairies" ] "TODO" (\tracker -> True)
    , Location "Colossus Freestanding PoH" "Collectable" [ "Desert Colossus" ] "TODO" (\tracker -> True)
    , Location "Colossus Deku Scrub Grotto Front" "GrottoNPC" [ "Desert Colossus", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "Colossus Deku Scrub Grotto Rear" "GrottoNPC" [ "Desert Colossus", "Deku Scrub", "Grottos" ] "TODO" (\tracker -> True)
    , Location "Colossus GS Bean Patch" "GS Token" [ "Desert Colossus", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Colossus GS Tree" "GS Token" [ "Desert Colossus", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Colossus GS Hill" "GS Token" [ "Desert Colossus", "Skulltulas" ] "TODO" (\tracker -> True)
    , Location "Colossus Gossip Stone" "HintStone" [] "TODO" (\tracker -> True)

    -- Haunted Wasteland
    , Location "Wasteland Bombchu Salesman" "NPC" [ "Haunted Wasteland" ] "TODO" (\tracker -> True)
    , Location "Wasteland Chest" "Chest" [ "Haunted Wasteland" ] "TODO" (\tracker -> True)
    , Location "Wasteland GS" "GS Token" [ "Haunted Wasteland", "Skulltulas" ] "TODO" (\tracker -> True)

    -- Miscellaneous Locations/Events/Drops/Hints "TODO" (\tracker -> True)
    , Location "Links Pocket" "Boss" [] "TODO" (\tracker -> True)
    , Location "Pierre Scarecrow" "Event" [] "TODO" (\tracker -> True)
    , Location "Deliver Rutos Letter" "Event" [] "TODO" (\tracker -> True)
    , Location "Master Sword Pedestal" "Event" [] "TODO" (\tracker -> True)
    , Location "Deku Baba Sticks" "Drop" [] "TODO" (\tracker -> True)
    , Location "Deku Baba Nuts" "Drop" [] "TODO" (\tracker -> True)
    , Location "Stick Pot" "Drop" [] "TODO" (\tracker -> True)
    , Location "Nut Pot" "Drop" [] "TODO" (\tracker -> True)
    , Location "Nut Crate" "Drop" [] "TODO" (\tracker -> True)
    , Location "Blue Fire" "Drop" [] "TODO" (\tracker -> True)
    , Location "Lone Fish" "Drop" [] "TODO" (\tracker -> True)
    , Location "Fish Group" "Drop" [] "TODO" (\tracker -> True)
    , Location "Bug Rock" "Drop" [] "TODO" (\tracker -> True)
    , Location "Bug Shrub" "Drop" [] "TODO" (\tracker -> True)
    , Location "Wandering Bugs" "Drop" [] "TODO" (\tracker -> True)
    , Location "Fairy Pot" "Drop" [] "TODO" (\tracker -> True)
    , Location "Free Fairies" "Drop" [] "TODO" (\tracker -> True)
    , Location "Wall Fairy" "Drop" [] "TODO" (\tracker -> True)
    , Location "Butterfly Fairy" "Drop" [] "TODO" (\tracker -> True)
    , Location "Gossip Stone Fairy" "Drop" [] "TODO" (\tracker -> True)
    , Location "Bean Plant Fairy" "Drop" [] "TODO" (\tracker -> True)
    , Location "Fairy Pond" "Drop" [] "TODO" (\tracker -> True)
    , Location "Big Poe Kill" "Drop" [] "TODO" (\tracker -> True)
    , Location "Ganondorf Hint" "Hint" [] "TODO" (\tracker -> True)
    ]
